batch_size: 3
height: 32
learning_rate: 0.0001
max_text_length: 50
model_path: models/crnn_lines
train_epochs: 10
train_workers: 30
vocab: '!"$%''(),-./0123456789:?ABCDEFGHIJKLMNOPQRSTUVWXYZ[]abcdefghijklmnopqrstuvwxyz'
width: 384
